### ISSUE TITLE
Little UX / Info To-Do List (Prep for Launch)

### ISSUE THREAD

**Issue by tayvano** [MrLuit/EtherScamDB#1]
- [x] On report page, change the red "no" button to read "No - I want to report an address / website"

- On layer two of "i'm not sure":
    - [x] Add other useful links (don't necessarily need to use all of them)
            - "create a new wallet" => https://myetherwallet.groovehq.com/knowledge_base/topics/how-do-i-create-a-new-wallet
            - https://myetherwallet.groovehq.com/knowledge_base/topics/protecting-yourself-and-your-funds
            - https://myetherwallet.groovehq.com/knowledge_base/topics/pro-tips-how-not-to-get-scammed-during-a-token-sale
           - https://myetherwallet.groovehq.com/knowledge_base/topics/call-to-action-help-us-phuck-these-phishers-up-please (edited)

- [x] On forms that are more than one step, add back button (if possible)

- [x] Update any buttons that don't give the user a more clear idea of what clicking the button will do 

- [x] On finishing pages (`Thanks for your Report`) add a third line of copy educating users about security: 
    - [x] Learn more about best practices and how to secure yourself: https://myetherwallet.groovehq.com/knowledge_base/topics/protecting-yourself-and-your-funds
    - or
    - [x] Get a Ledger or TREZOR Hardware wallet. Add affiliate links here. You can create links @ https://www.ledgerwallet.com/affiliates & https://shop.trezor.io/user/profile/affiliate/
    - or
    - [x] You can also help make sure people aren't able to reach this site in the future. Please take a moment to report to the browsers:
           - https://safebrowsing.google.com/safebrowsing/report_phish/
           - https://safebrowsing.google.com/safebrowsing/report_badware/
           - If have IE / Edge, report there: https://support.microsoft.com/en-us/help/930167/how-to-report-a-phishing-web-site
           - Report Google ad: https://support.google.com/adwords/troubleshooter/4578507?visit_id=1-636363900698406880-2129187164&rd=1
           - Notify host regarding malicious website / DMCA / copyright violation / trademark violation
           - Notify registrar regarding malicious website / DMCA / copyright violation / trademark violation
           - Notify SSL Cert Issuer of misuse of cert / malicious / phishing website

- [ ] Add these HW wallet affiliate links to the footer as well.

- [x] Add buttons or make the entire square on homepage a link to Github, Report, Etc.

- [ ] Add square for hardware wallet stuff w/ affiliate links

- [ ] Under knowledge, link to simple links page that just has valuable resources for people. Things like the links I provided above,  any reddit threads you find in the future that are useful, etc. You can find some good resources here: https://myetherwallet.groovehq.com/knowledge_base/topics/resources-for-diving-deeper

**Comment by MrLuit** [comment]
Instead of adding the hardware wallet affiliate links to footer and homepage, I added them to FAQ and at the end of the report function.

Also, I'm not sure about the last point because it doesn't really fit in with the current design.

Other than that, all features have been implemented.
